  <!-- Start Property header  -->

  <section id="aa-property-header">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="aa-property-header-inner">
            <h2>Privacy Policy</h2>
            <ol class="breadcrumb">
            <li><a href="<?php echo base_url();?>">HOME</a></li>            
            <li class="active">Privacy Policy</li>
            </ol>
          </div>
        </div>
      </div>
    </div>
  </section> 
  <!-- End Property header  -->

  <!-- Start Properties  -->
  <section id="aa-properties">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="aa-properties-content">
            <!-- start properties content head -->
            <!-- Start properties content body -->
            <div class="aa-properties-content-body">
            <h3 class="aa-property-header-inner">Privacy Policy</h3>
            <strong id="docs-internal-guid-fec54575-1823-3c11-f6f7-3824f839dcb2">
            <p dir="ltr">Personal Information<br>
              Non-Account Activity. No information / registration details are required to access the Website.<br>
              <br>
              Account-Related Activity<br>
              Certain other activities on the Website like uploading information require the User to have a Registered User Account. The User is required to provide some personal information when the User creates an account, which personal information includes the User's email address, which is used to protect the User's account from unauthorized access. A Registered User Account allows the User to access many of the Website's services that require registration.<br>
              <br>
              Usage Information<br>
              The Site Owner may record information about the User's usage, such as when the User used the Website, the favourites the User subscribed to, the contacts the User communicated with, the information the User has viewed and the frequency and size of data transfers, as well as the information the User displayed on the Website (including UI elements, settings, and other information). <br>
              <br>
              Content Uploaded to Site<br>
              Any personal information or information that the User voluntarily discloses online becomes publicly available and can be collected and used by others.<br>
              <br>
              Users<br>
              If the User submits personally identifiable information to the Site Owner through the Website, the Site Owner may use the User's personal information to operate, maintain, and provide the User with general and personalized features and functionality on the Website, and process any flagging activity or correspondence the User sends to the Site Owner.<br>
              The User's account name is displayed to other Users when the User uploads information or sends messages through the Website and other Users can contact the User through messages and comments. Any information that the User submits to the Website may be redistributed through the internet and other media channels, and may be viewed by the general public.<br>
              The Site Owner does not use the User's email address or other personally identifiable information to send commercial or marketing messages without the User's consent or except as part of a specific program or feature for which the User will have the ability to opt-in or opt-out. The Site Owner may, however, use the User's email address without further consent for non-marketing or administrative purposes (such as notifying the User of major Website changes or for User service purposes).<br>
              The Site Owner uses both the User's personally identifiable information and certain non-personally-identifiable information (such as anonymous user usage data, cookies, IP addresses, browser type, clickstream data, etc.) to improve the quality and design of the Website and to create new features, promotions, functionality, and services by storing, tracking, analyzing, and processing User preferences and trends, as well as User activity and communications.<br>
              The Site Owner uses cookies, clear gifs, and log file information to: (a) store information so that the User will not have to re-enter the same during the User's next visit; (b) provide customised, personalized content and information; (c) monitor the effectiveness of the Website's marketing campaigns; (d) monitor aggregate metrics such as total number of visitors, pages viewed, etc.; and (e) track the User's entries, submissions, and status in promotions, sweepstakes, and contests.<br>
              <br>
              Information that is publicly available<br>
              When the User creates an account on the Website, some information about the User's account and the User's account activity will be provided to other Users of the Website. This may include the date the User opened the User's account, the date the User last logged into the User's account, the User's age (if the User choose to make it public), the country and the number of / information relating to real estate that the User has visited. <br>
              The User's account name is displayed to other Users when the User engages in certain activities on the Website, such as when the User uploads information or sends messages through the Website. Other Users can contact the User through messages and comments.<br>
              The User may also choose to add personal information that will be visible to other Users.<br>
              Any information that the User submits to the Website can be redistributed through the internet and other media by the Site Owner, without obtaining any consent from the User, and may be viewed by the general public.<br>
              <br>
              Use of IndianLandMarket Cookies</p>
            <p dir="ltr">This web site uses cookies to raised the users expertise whereas visiting the web site. Wherever applicable this web site uses a cookie system permitting the employment on their 1st visit to the web site to permit or veto the use of cookies on their Mobile / laptop / portable computer. This complies with recent legislation necessities for websites to get specific consent from users before abandoning or reading files like cookies on a user's laptop / device. Cookies are little files saved to the user's computers disk drive that track, save and store data concerning the user's interactions and usage of the web site. this permits the web site, through its server to produce the users with a tailored expertise inside this web site. Users are suggested that if they need to deny the employment and saving of cookies from this web site on to their computers disk drive they must take necessary steps inside their net browsers security settings to dam all cookies from this web site and its external serving vendors.</p>
            <p dir="ltr">This web site uses trailing software package to observe its guests to raised perceive however they use it. This software package is provided by Google Analytics that uses cookies to trace traveller usage. The software package can save a cookie to your computers disk drive so as to trace and monitor your engagement and usage of the web site, however won't store, save or collect personal data. you'll be able to browse Google's privacy policy here for any data [ http://www.google.com/privacy.html ].</p>
            <p dir="ltr"><br>
              <br>
              Third-party Advertisers, Links to Other Sites<br>
              The Site Owner allows other companies, called third-party ad servers or ad networks, to display advertisements within the Website. These third-party ad servers or ad networks use technology to send advertisements and links that appear on the Website directly to the User's browser. They automatically receive the User's IP address when this happens. They may also use other technology (such as cookies, JavaScript, or Web Beacons) to measure the effectiveness of their advertisements and to personalize the advertising content the User sees.<br>
              The Site Owner does not provide any personally identifiable information to these third-party ad servers or ad networks without the User's consent or except as part of a specific program or feature for which the User will have the ability to opt-in or opt-out. However, please note that if an advertiser asks the Site Owner to show an advertisement to a certain audience and the User responds to that advertisement, the advertiser or ad-server may conclude that the User fits the description of the audience they are trying to reach. The advertiser may also use information regarding the User's use of the Website, such as the number of times the User viewed an ad (but not any personally identifiable information), to determine which ads to deliver to the User.<br>
              The User should consult the respective privacy policies of these third-party ad servers or ad networks for more information on their practices and for instructions on how to opt-out of certain practices. The Website's privacy policy does not apply to, and the Site Owner cannot control the activities of, such other advertisers or web sites. Any data obtained by third-party ad servers subsequently shared with the Site Owner is maintained and dealt with by the Site Owner in accordance with this privacy policy.<br>
              <br>
              More Information<br>
              For questions concerning the Website or the User's account, please read the Help page.<br>
              For more information about the Website's privacy practices, write to the Site Owner<br>
              <br>
              Disclaimer of warranties<br>
              This Website service is provided on an &quot;as is&quot; and &quot;as available&quot; basis. The Site Owner expressly disclaims all warranties of any kind, whether express or implied or statutory, including, but not limited to the implied warranties of merchantability, fitness for a particular purpose, data accuracy &amp; completeness in the Website or any part thereof or any transactions entered into through the Website, and any warranties relating to viruses and non-infringement in the Website or any transactions entered into, through the Website. The Site Owner makes no representations or warranties, either express or implied that the use of the Website will not infringe any patent, copyright or other right of any third party. No advice or information, whether oral or written, obtained by the User through, or from, the Website shall create any warranty not expressly stated herein.</p>
            </strong>
            <p><strong>              The Site Owner makes no warranty that the Website will meet the User's requirements, or that the Website will be uninterrupted, timely, secure, or error free; nor does the Site Owner make any warranty as to the results that may be obtained from the use of the Website or as to the accuracy or reliability of the information/material on the Website.</strong></p>
            <h4 ><em>PRIVACY</em></h4>
            <p ><strong>Personal Information</strong><br>
              Non-Account Activity. No information / registration details are required to access the Website.<br>
              <br>
              <strong>Account-Related Activity</strong><br>
              Certain other activities on the Website like uploading information require the User to have a Registered User Account. The User is required to provide some personal information when the User creates an account, which personal information includes the User's email address, which is used to protect the User's account from unauthorized access. A Registered User Account allows the User to access many of the Website's services that require registration.<br>
              <br>
              <strong>Usage Information</strong><br>
              The Site Owner may record information about the User's usage, such as when the User used the Website, the favourites the User subscribed to, the contacts the User communicated with, the information the User has viewed and the frequency and size of data transfers, as well as the information the User displayed on the Website (including UI elements, settings, and other information). If the User is logged in, the Site Owner may associate that information with the User's account. The Site Owner may use clear GIFs (a.k.a. "Web Beacons") in HTML-based emails sent to Users to track which emails are opened by the recipients.<br>
              <br>
              <strong>Content Uploaded to Site</strong><br>
              Any personal information or information that the User voluntarily discloses online becomes publicly available and can be collected and used by others.<br>
              <br>
              <strong>Users</strong><br>
              If the User submits personally identifiable information to the Site Owner through the Website, the Site Owner may use the User's personal information to operate, maintain, and provide the User with general and personalized features and functionality on the Website, and process any flagging activity or correspondence the User sends to the Site Owner.<br>
              The User's account name is displayed to other Users when the User uploads information or sends messages through the Website and other Users can contact the User through messages and comments. Any information that the User submits to the Website may be redistributed through the internet and other media channels, and may be viewed by the general public.<br>
              The Site Owner does not use the User's email address or other personally identifiable information to send commercial or marketing messages without the User's consent or except as part of a specific program or feature for which the User will have the ability to opt-in or opt-out. The Site Owner may, however, use the User's email address without further consent for non-marketing or administrative purposes (such as notifying the User of major Website changes or for User service purposes).<br>
              The Site Owner uses both the User's personally identifiable information and certain non-personally-identifiable information (such as anonymous user usage data, cookies, IP addresses, browser type, clickstream data, etc.) to improve the quality and design of the Website and to create new features, promotions, functionality, and services by storing, tracking, analyzing, and processing User preferences and trends, as well as User activity and communications.<br>
              The Site Owner uses cookies, clear gifs, and log file information to: (a) store information so that the User will not have to re-enter the same during the User's next visit; (b) provide customised, personalized content and information; (c) monitor the effectiveness of the Website's marketing campaigns; (d) monitor aggregate metrics such as total number of visitors, pages viewed, etc.; and (e) track the User's entries, submissions, and status in promotions, sweepstakes, and contests.<br>
              <br>
              <strong>Information that is publicly available</strong><br>
              When the User creates an account on the Website, some information about the User's account and the User's account activity will be provided to other Users of the Website. This may include the date the User opened the User's account, the date the User last logged into the User's account, the User's age (if the User choose to make it public), the country and the number of / information relating to real estate that the User has visited.&#160;<br>
              The User's account name is displayed to other Users when the User engages in certain activities on the Website, such as when the User uploads information or sends messages through the Website. Other Users can contact the User through messages and comments.<br>
              The User may also choose to add personal information that will be visible to other Users.<br>
              Any information that the User submits to the Website can be redistributed through the internet and other media by the Site Owner, without obtaining any consent from the User, and may be viewed by the general public.<br>
              <br>
              <strong>The User's Choices</strong><br>
              The User may, of course, decline to submit personally identifiable information through the Website, in which case the Website may not be able to provide certain services to the User. Some advanced features may, for authentication purposes, require the User to sign up for other services. The privacy notices of those services govern the use of the User's personal information associated with them.&#160;<br>
              The User may update or correct the User's personal profile information at any time.<br>
              <br>
              <strong>Third-party Advertisers, Links to Other Sites</strong><br>
              The Site Owner allows other companies, called third-party ad servers or ad networks, to display advertisements within the Website. These third-party ad servers or ad networks use technology to send advertisements and links that appear on the Website directly to the User's browser. They automatically receive the User's IP address when this happens. They may also use other technology (such as cookies, JavaScript, or Web Beacons) to measure the effectiveness of their advertisements and to personalize the advertising content the User sees.<br>
              The Site Owner does not provide any personally identifiable information to these third-party ad servers or ad networks without the User's consent or except as part of a specific program or feature for which the User will have the ability to opt-in or opt-out. However, please note that if an advertiser asks the Site Owner to show an advertisement to a certain audience and the User responds to that advertisement, the advertiser or ad-server may conclude that the User fits the description of the audience they are trying to reach. The advertiser may also use information regarding the User's use of the Website, such as the number of times the User viewed an ad (but not any personally identifiable information), to determine which ads to deliver to the User.<br>
              The User should consult the respective privacy policies of these third-party ad servers or ad networks for more information on their practices and for instructions on how to opt-out of certain practices. The Website's privacy policy does not apply to, and the Site Owner cannot control the activities of, such other advertisers or web sites. Any data obtained by third-party ad servers subsequently shared with the Site Owner is maintained and dealt with by the Site Owner in accordance with this privacy policy.<br>
              <br>
              <strong>More Information</strong><br>
              For questions concerning the Website or the User's account, please read the Help page.<br>
              For more information about the Website's privacy practices, write to the Site Owner<br>
              <br>
              <strong>Disclaimer of warranties</strong><br>
              This Website service is provided on an "as is" and "as available" basis. The Site Owner expressly disclaims all warranties of any kind, whether express or implied or statutory, including, but not limited to the implied warranties of merchantability, fitness for a particular purpose, data accuracy & completeness in the Website or any part thereof or any transactions entered into through the Website, and any warranties relating to viruses and non-infringement in the Website or any transactions entered into, through the Website. The Site Owner makes no representations or warranties, either express or implied that the use of the Website will not infringe any patent, copyright or other right of any third party. No advice or information, whether oral or written, obtained by the User through, or from, the Website shall create any warranty not expressly stated herein. <br>
              The Site Owner makes no warranty that the Website will meet the User's requirements, or that the Website will be uninterrupted, timely, secure, or error free; nor does the Site Owner make any warranty as to the results that may be obtained from the use of the Website or as to the accuracy or reliability of the information/material on the Website. </p>
            <h4 ><em>Limitation of Liability</em></h4>
            <p >The User agrees that Site Owner shall not be liable for any direct, indirect, incidental, special or consequential damages, (including, but not limited to, damages caused by personal injury, loss of profits, use, data or other intangible, business interruption, loss of privacy, or any other pecuniary loss) to the User or any third party resulting from the (i) errors, mistakes, or inaccuracies of content, (ii) Personal injury or property damage, of any nature whatsoever, resulting from the User's access to and use of the Website, (iii) any unauthorized access to or use of the Website and secure servers, and/or any and all personal information and/or financial information stored therein, (iv) any interruption or cessation of transmission to or from the Website, (v) any bugs, viruses, trojan horses, or the like, which may be transmitted to or through the Website by any third party, and/or (vi) any errors or omissions in any content or for any loss or damage of any kind incurred as a result of the use by the User of any content posted, emailed, transmitted, or otherwise made available on the Website, whether based on warranty, contract, tort, or any other law, and whether or not the Site Owner is advised of the possibility of such damages. The foregoing limitation of liability shall apply to the fullest extent permitted by law. The Registered User specifically acknowledges that the Site Owner is only providing a platform at its absolute discretion to share certain information and shall not be liable for:-<br>
              User submissions or the defamatory, offensive, or illegal conduct of any third party and that the risk of harm or damage from the foregoing rests entirely with the User.<br>
              The use or the inability to use the services provided by the Website.<br>
              The delivery or the inability to deliver the services provided by the Website.<br>
              The performance or the inability to perform the services provided by the Website.<br>
              Any costs or consequences resulting from the above acts/omissions or resulting from the access to, or alteration of User's transmissions or data. <br>
              The User further agrees that the Site Owner shall not be liable to the User or any third party for any damages arising from any error, interruption, suspension or termination of, or in, the Website, including but not limited to direct, indirect, incidental, special, consequential or exemplary damages, whether such interruption, suspension or termination was justified or not, negligent or intentional, inadvertent or advertent. <br>
              This Website may contain links to websites operated by parties other than the Site Owner, which will cause the User to leave this Website or have access to other websites. The User's use of each such other websites is subject to the terms of use and other terms and guidelines, if any, contained within each such other website. In the event that any of the terms contained herein conflict with the terms of use or other terms and guidelines contained within any such website, then the terms of use and other terms and guidelines for such other website shall prevail with regard to the use of the website. The linked websites are not under the control of the Site Owner and the Site Owner is not responsible for the contents of any linked web site or any link contained in a linked web site, or any changes or updates to such web sites. The Site Owner is providing these links to the User only as a convenience, and the inclusion of any link does not imply endorsement by the Site Owner of the other website. <br>
              The User agrees that the Site Owner is not responsible for the accuracy, completeness or availability of information, content and materials found on other websites that link to or from the Website. The Site Owner cannot ensure that the User will be satisfied with any services that the User purchases from a third-party/ other website that links to or from the Website or third-party information, content or materials contained on this Website (including, without limitation, User-Generated Content contained in the Website). <br>
              The Site Owner does not invite, offer, recommend and/or endorse any of the information regarding any property/real estate including but not limited to the title of the owner, rates charged, amenities provided or quality of construction etc , nor has the Site Owner taken any steps to confirm the accuracy, completeness or reliability of, any information, content or materials contained on this Website or on any other third-party website. The Site Owner does not make any representations or warranties as to the security of any information, content or materials (including, without limitation, credit card and other personal information) the User might be requested to give to any third party. The User hereby irrevocably waives any claims against the Site Owner with respect to information, content and materials contained on the Websites (including, without limitation, User-Generated Content), on third party websites, and any information, content and materials Users provide to such third party websites (including, without limitation, credit card and other personal information). The Site Owner strongly encourages the Users to make whatever investigation the User feels necessary or appropriate before proceeding with any online or offline transaction with any third party. Users are also strongly advised to independently verify the authenticity of any offers received by them. The Site Owner does not endorse investment in any of the projects and User's investments shall be entirely at the risk and responsibility of the User. </p>
            <h4 ><em>General</em></h4>
            <p >The Site Owner reserves the absolute discretion to modify the Website or to amend / supplement any of these Terms Of Use at any time. The abovementioned amendments / supplements shall automatically become binding on the User, as soon as the said amendment or supplement is made to the Terms of Use, and is published on the Website. <br>
              The Site Owner may sub-contract and/or employ any affiliate to carry out any of its obligations under these Terms of Use. The Site Owner may transfer or assign its rights and obligations under this contract to any third party without requiring any consent of the Registered Users or any other Users. The Registered User agrees that his/her User ID and password shall be used by him / her alone and shall not be transferred / assigned or permitted to be used by any other person. <br>
              The User hereby grants to the company a non-exclusive, worldwide, royalty-free, irrevocable, sub-license able (through multiple tiers) right to exercise all copyright and publicity rights, in any existing or future media, known or unknown, over the material or User Data that may be required to display the listings. <br>
              The Website, these Terms of Use and the User's use of the Website is governed solely by Indian law irrespective of where the whole or any part of the data or Website may be physically located and without regard to conflict of law principles in other jurisdictions. Use of this Website is unauthorized and prohibited in any jurisdiction that does not give effect to all provisions of these Terms including without limitation, this paragraph. The Site Owner accepts no liability whatsoever, direct or indirect for non-compliance by the user with the laws of any country other than that of the Republic of India. The User agrees that the Courts in Kerala, India, alone shall have jurisdiction with regard to any dispute between the User and the Site Owner excluding all other Courts anywhere in the world that may otherwise have had such jurisdiction.</p>
            <p>&nbsp;</p>
            </div>
            
          </div>
        </div>
     
      </div>
    </div>
  </section>
  <!-- / Properties  -->
